# Generated by Django 5.0 on 2023-12-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_booking', '0002_alter_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(verbose_name='Дата выезда'),
        ),
    ]
