# Generated by Django 5.0 on 2023-12-23 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_booking', '0004_remove_room_available_room_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_id', to='my_booking.room', verbose_name='Комната'),
        ),
    ]
