# Generated by Django 5.0 on 2023-12-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_booking', '0009_alter_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг'),
        ),
    ]
