# Generated by Django 5.0 on 2023-12-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_booking', '0011_alter_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='discription',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
